language: node_js
node_js:
  - "0.12"

before_install:
  - export TZ=Europe/Paris

services:
  - mongodb
  - redis-server
  - rabbitmq

install:
  - npm install -g mocha jshint
  - npm install

before_script:
  - mocha --version
  - node --version

script:
  - make test
